### ISSUE TITLE
rq 1.12 breaks unit tests using fakeredis

### ISSUE THREAD

**Issue by ronlut** [rq/rq#1762]
Hey, great work on the lib :)

Version 1.12 breaks all unit tests involving rq and fakeredis, [as recommended in RQ's documentation](https://python-rq.org/docs/testing/#running-jobs-in-unit-tests), because fakeredis [doesn't implement XREVRANGE](https://github.com/cunla/fakeredis-py/blob/master/docs/redis-commands/unimplemented_commands.md).

Any suggested solution to that problem?

partial traceback showing the problem:
```
../../../.venv/lib/python3.8/site-packages/rq/queue.py:581: in enqueue_job
    job = self.run_sync(job)
../../../.venv/lib/python3.8/site-packages/rq/queue.py:597: in run_sync
    job.success_callback(job, self.connection, job.result)
../../../.venv/lib/python3.8/site-packages/rq/job.py:586: in result
    self._cached_result = self.latest_result()
../../../.venv/lib/python3.8/site-packages/rq/job.py:607: in latest_result
    return Result.fetch_latest(self, serializer=self.serializer)
../../../.venv/lib/python3.8/site-packages/rq/results.py:136: in fetch_latest
    response = job.connection.xrevrange(cls.get_key(job.id), '+', '-', count=1)
../../../.venv/lib/python3.8/site-packages/redis/client.py:2627: in xrevrange
    return self.execute_command('XREVRANGE', name, *pieces)
../../../.venv/lib/python3.8/site-packages/redis/client.py:901: in execute_command
    return self.parse_response(conn, command_name, **options)
../../../.venv/lib/python3.8/site-packages/redis/client.py:915: in parse_response
    response = connection.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = FakeConnection<server=<fakeredis._server.FakeServer object at 0x124fd4370>,db=0>
disable_decoding = False

    def read_response(self, disable_decoding=False):
        if not self._server.connected:
            try:
                response = self._sock.responses.get_nowait()
            except queue.Empty:
                raise redis.ConnectionError(msgs.CONNECTION_ERROR_MSG)
        else:
            response = self._sock.responses.get()
        if isinstance(response, redis.ResponseError):
>           raise response
E           redis.exceptions.ResponseError: unknown command 'xrevrange'
```

**Comment by sduenas** [comment]
You can update `fakeredis` to `2.2.0`. It should resolve the problem.

**Comment by ronlut** [comment]
Thanks @sduenas, tried but same problem.. Anything special about this version? [It's not implemented there as well](https://github.com/cunla/fakeredis-py/blob/v2.2.0/REDIS_COMMANDS.md#unimplemented-commands) (I am using 2.5.0, tried 2.2.0 now and still the same problem)

**Comment by lowercase00** [comment]
You probably have two options:
- Use a real Redis server with in sync mode
- Pin version to 1.11.x

No entirely sure if there are options (or even if it would make sense) to replace the code for the sake of supporting FakeRedis. If that is the case, great, if it's not, we should update the docs to remove FakeRedis. 

At last contributing to FakeRedis to add the command can also be a great idea.

I'll leave it up to @selwin.

**Comment by ronlut** [comment]
Thanks @lowercase00, yeah, thought about implementing it in fakeredis, will do if no simpler solution exists.
Anyway, I think it goes a bit deeper, rq codebase have [at least 1 place which adjusts the flow for fakeredis](https://github.com/rq/rq/blob/master/rq/utils.py#L314). Whether unit tests with fakeredis use-case is to be supported or not is indeed @selwin's decision.

**Comment by sduenas** [comment]
> Thanks @sduenas, tried but same problem.. Anything special about this version? [It's not implemented there as well](https://github.com/cunla/fakeredis-py/blob/v2.2.0/REDIS_COMMANDS.md#unimplemented-commands) (I am using 2.5.0, tried 2.2.0 now and still the same problem)

You are right. What we did was to bump fakeredis to `2.2` but we had to install `rq<1.12.0`, as @lowercase00 commented.

Sorry for the noise.

**Comment by selwin** [comment]
> Whether unit tests with fakeredis use-case is to be supported or not is indeed @selwin's decision.

I don't intentionally break fakeredis support, if there's an easy way around this, I'd be happy to accept a patch.

**Comment by lowercase00** [comment]
I'm not sure if it would be that simple to implement the `STREAM` type in FakeRedis. This is currently being used in the `results` module. So unless we handle the result using a different data type (i guess it was implemented with the Sorted Set before the Stream), I imagine this will stay that way for a while. If that's the case it might be worth adding that to the docs.

**Comment by selwin** [comment]
If FakeRedis doesn't implement Redis streams, then I don't think there's much we can do. I don't think it's wise to limit the use of newer Redis features based on the availability of mocking libraries.

I'll close this issue then.

**Comment by lowercase00** [comment]
Related to #1809
